name = "afterain-personal-site"
main = "src/index.js"
compatibility_date = "2026-08-05"

[assets]
directory = "./public"

[vars]
# 收信地址和发件地址建议在 Cloudflare Dashboard 的 Variables 中配置。
# TO_EMAIL = "your@email.com"
# FROM_EMAIL = "hello@yourdomain.com"

[[send_email]]
name = "EMAIL"
remote = true
