name = "afterain-personal-site"
main = "src/index.js"
compatibility_date = "2026-08-05"

[assets]
directory = "./public"

[vars]
# TO_EMAIL = "your@email.com"
# FROM_EMAIL = "hello@yourdomain.com"

[[send_email]]
name = "EMAIL"
remote = true

# 匿名信限流
[[kv_namespaces]]
binding = "LETTER_RATE_LIMIT"
id = "58fd3397a30f4929a4c760b454c09a4e"

# 网站内容
[[kv_namespaces]]
binding = "SITE_KV"
id = "92fd195d8c064c56851659ee6414404f"